---
name: Data Gatherer

on:
  push:
    branches:
    - enterprise
  schedule:
    # Hourly
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  generate-data:
    name: Generate json data for web ui

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: pip install .
    - name: Display API rate-limit
      run: curl -I https://api.github.com/users/octocat
    - run: ./bin/generate-enterprise-data.sh docs/enterprise-data.json
      env:
          GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/configure-pages@v2
    - uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs'
    - uses: actions/deploy-pages@v1
      id: deployment

